# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

Vagrant.configure(2) do |config|
  config.vm.box = "debian/jessie64"
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end
  config.vm.provision "file", source: "./vagrant-files/grubfile", destination: "/tmp/grubfile"
  config.vm.provision "shell", inline: "sudo mv /tmp/grubfile /etc/default/grub"
  config.vm.provision "shell", inline: "sudo update-grub2"
  config.vm.provision "shell", inline: "/bin/grep -v swap /etc/fstab | sudo tee /etc/fstab"
end
