kind: PersistentVolume
apiVersion: v1
metadata:
  name: openvpn
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/kubedata/openvpn"

---
    
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: openvpn
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
