kind: PersistentVolume
apiVersion: v1
metadata:
  name: diaspora-postgres
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/kubedata/diaspora_postgres"

---
    
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: diaspora-postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
