apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: fear
  namespace: rsablog
spec:
  gateways:
  - istio-system/istio-ingressgateway
  hosts:
  - fearisthevibekiller.com
  http:
  - name: static
    match:
    - uri:
        prefix: /
    route:
    - destination:
        host: nginx.rsablog.svc.cluster.local
        port:
          number: 80
