---
- hosts: all
  become: yes
  become_method: sudo
  tasks:
  - name: Disable swap
    command: swapoff -a
  - name: INTSALL essentials
    apt:
      name: "{{ packages }}"
    vars:
      packages:
        - vim
        - tmux
        - wget
        - apt-transport-https
        - ca-certificates
        - software-properties-common
        - iptables-persistent
  - template:
      src: ./etc/iptables.up.rules.j2
      dest: /etc/iptables.up.rules
  - name: drop firewall setup script
    copy:
      src: ./etc/network/if-pre-up.d/iptables
      dest: /etc/network/if-pre-up.d/iptables
      mode: 0755
  - name: apply fw rules
    shell: /sbin/iptables-restore < /etc/iptables.up.rules
  - name: ADD docker repository key
    apt_key:
      url: https://download.docker.com/linux/debian/gpg
      id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
      state: present
  - name: ADD docker repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/debian jessie stable
      state: present
  - name: ADD k8s repo key
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      id: 54A647F9048D5688D7DA2ABE6A030B21BA07F4FB
      state: present
  - name: ADD k8s repo
    apt_repository:
      repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
      state: present
  - name: INSTALL docker and k8s
    apt:
      name: "{{ packages }}"
    vars:
      packages:
        - docker-ce=17.03.2~ce-0~debian-jessie
        - kubeadm
        - kubelet
  - name: make k8s persistent volume subdir for openvpn
    file: path=/mnt/kubedata/openvpn state=directory 
