---
- hosts: all
  become: yes
  become_method: sudo
  gather_facts: no
  pre_tasks:
  - name: install python
    raw: sudo apt-get -y install python3
  tasks:
  - name: Disable swap
    command: swapoff -a
  - name: INTSALL essentials
    apt:
      name: "{{ packages }}"
    vars:
      packages:
        - vim
        - tmux
        - wget
        - curl
        - net-tools
        - apt-transport-https
        - ca-certificates
        - software-properties-common
        - iptables-persistent
  - template:
      src: ./etc/iptables.up.rules.j2
      dest: /etc/iptables.up.rules
  - template:
      src: ./etc/ip6tables.up.rules.j2
      dest: /etc/ip6tables.up.rules
  - name: drop firewall setup script
    copy:
      src: ./etc/network/if-pre-up.d/iptables
      dest: /etc/network/if-pre-up.d/iptables
      mode: 0755
  - name: apply fw rules
    shell: /sbin/iptables-restore < /etc/iptables.up.rules
  - name: apply fw6 rules
    shell: /sbin/ip6tables-restore < /etc/ip6tables.up.rules
  - name: make k8s persistent volume subdir for openvpn
    file: path=/mnt/kubedata/openvpn state=directory
  - name: grab k3s installer
    get_url: url=https://get.k3s.io dest=/tmp/k3s.sh mode=0755
  - name: install k3s
    shell: /tmp/k3s.sh
  - name: FETCH kubectl config file
    fetch:
      src: /etc/rancher/k3s/k3s.yaml
      dest: ./kubeconfig/config
