---
- hosts: vagrant
  remote_user: ubuntu
  become: yes
  tasks:
  - name: INTSALL essentials
    action: >
      {{ ansible_pkg_mgr }} name={{ item }} state=present update_cache=yes
    with_items:
      - vim
      - tmux
      - apt-transport-https
      - ca-certificates
      - software-properties-common
  - name: ADD docker repository key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
      state: present
  - name: ADD docker repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu xenial stable
      state: present
  - name: ADD k8s repo key
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      id: D0BC747FD8CAF7117500D6FA3746C208A7317B0F
      state: present
  - name: ADD k8s repo
    apt_repository:
      repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
      state: present
  - name: INSTALL docker and k8s
    action: >
      {{ ansible_pkg_mgr }} name={{ item }} state=present update_cache=yes
    with_items:
      - docker-ce=17.03.2~ce-0~ubuntu-xenial
      - kubeadm
      - kubelet
  - name: CREATE a cluster master node
    command: kubeadm init --pod-network-cidr=192.168.99.0/24 --apiserver-cert-extra-sans=vagrant-k8s
