---
- hosts: all
  become: yes
  become_method: sudo
  tasks:
  - name: CREATE a cluster master node
    command: kubeadm init --pod-network-cidr=192.168.0.0/16
  - name: FETCH kubectl config file
    fetch:
      src: /etc/kubernetes/admin.conf
      dest: ./kubeconfig
