#!/bin/bash

#istioctl manifest generate \
istioctl manifest apply \
  --set addonComponents.prometheus.enabled=false \
  --set values.gateways.istio-ingressgateway.sds.enabled=true \
  --set values.global.k8sIngress.enabled=true \
  --set values.global.k8sIngress.enableHttps=true \
  --set values.pilot.resources.requests.memory=512Mi
#  --log_output_level all:debug
#  --set values.global.k8sIngress.gatewayName=ingressgateway

#
# Don't forget to patch the memory request on the istiod deployment!
#

# enable cert-manager => istio integration via SDS protocol
kubectl -n istio-system \
  patch gateway istio-autogenerated-k8s-ingress --type=json \
  -p='[{"op": "replace", "path": "/spec/servers/1/tls", "value": {"credentialName": "ingress-cert", "mode": "SIMPLE", "privateKey": "sds", "serverCertificate": "sds"}}]'

# enable http -> https redirect (dont do this if ACME verification is happening for the first time!)
kubectl -n istio-system \
  patch gateway istio-autogenerated-k8s-ingress --type=json \
  -p='[{"op": "replace", "path": "/spec/servers/0/tls", "value": {"httpsRedirect": true}}]'

kubectl create ns cert-manager

# https://github.com/jetstack/cert-manager/releases/download/v0.14.0/cert-manager.yaml
kubectl apply -f cert-manager.yaml

# setup lets encrypt prod ACME provider
kubectl apply -f prod-cert-ingress.yaml
