apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: ingress-cert
  namespace: istio-system
spec:
  secretName: ingress-cert
  issuerRef:
    name: letsencrypt-stage
    kind: ClusterIssuer
  commonName: rob.salmond.ca
  dnsNames:
  - rob.salmond.ca
